Added check if we have registration id

diff --git a/dehydrated b/dehydrated
--- a/dehydrated
+++ b/dehydrated
@@ -792,7 +792,14 @@ command_account() {
   NEW_ACCOUNT_KEY_JSON=${ACCOUNT_KEY_JSON}.$$
   REG_ID=$(cat ${ACCOUNT_KEY_JSON} | get_json_int_value id)
 
-  # If an email for the contact has been provided then adding it to the registration request
+  # Check if we have the registration id
+  if [[ -z "${REG_ID}" ]]; then
+    printf '\n'
+    printf 'Error retrieving registration id.\n'
+    exit 1
+  fi
+
+  # If an email for the contact has been provided then adding it to the registered account
   if [[ "${FAILED}" = "false" ]]; then
     if [[ -n "${CONTACT_EMAIL}" ]]; then
       (signed_request "${CA_REG}"/${REG_ID} '{"resource": "reg", "contact":["mailto:'"${CONTACT_EMAIL}"'"]}' > "${NEW_ACCOUNT_KEY_JSON}") || FAILED=true
