Include name of script when exiting on a fatal error (fixes #481)

diff --git a/dehydrated b/dehydrated
--- a/dehydrated
+++ b/dehydrated
@@ -415,7 +415,7 @@ _sed() {
 
 # Print error message and exit with error
 _exiterr() {
-  echo "ERROR: ${1}" >&2
+  echo "$0: ERROR: ${1}" >&2
   exit 1
 }
 
